
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx --yes tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // 마이그레이션 등 CLI는 Neon 직접 연결(풀러 미경유) 주소를 사용
    url: env("DATABASE_URL_UNPOOLED"),
  },
});
